### ISSUE TITLE
[gamemode] 该插件捕获服务端log范围太过宽泛

### ISSUE THREAD

**Issue by Ra1ny-Yuki** [577fkj/MCDR-plugins#2]
由于其他插件同样使用同样的方式捕获 `data get` 服务端返回的坐标信息，故在其他插件工作时同样会触发 `gamemode` ， `gamemode` 应当仅在玩家执行切换模式指令后才检测，逻辑参考可参阅 [Here](https://github.com/TISUnion/Here)

**Comment by 577fkj** [comment]
https://github.com/577fkj/MCDR-Gamemode
