### ISSUE TITLE
和here插件发生冲突

### ISSUE THREAD

**Issue by 1415ddfer** [577fkj/MCDR-plugins#3]
![屏幕截图 2022-01-11 113245](https://user-images.githubusercontent.com/94663994/148876832-883d8bbe-6575-43d8-bc65-e3b0c02d283f.png)

**Comment by 1415ddfer** [comment]
环境：
MCDR 2.3
here 1.1.2
望更新玩家选择器

**Comment by 577fkj** [comment]
https://github.com/577fkj/MCDR-Gamemode
